/**
 * CLI help system with MVI progressive disclosure.
 *
 * @remarks
 * Three levels of help:
 * - Level 0: `versionguard help` — topic index
 * - Level 1: `versionguard help <topic>` — focused topic content
 * - Level 2: `versionguard help --llm` — full API context (forge-ts llms.txt)
 *
 * JSON output uses the forge-ts CKM (Codebase Knowledge Manifest)
 * for machine-readable operational knowledge.
 *
 * @packageDocumentation
 */

// Embedded at build time by Vite's ?raw import
import ckmRaw from '../../docs/ckm.json?raw';
import llmsSummary from '../../docs/llms.txt?raw';

import { type HelpTopic, TOPICS } from './topics';

export { type HelpTopic, TOPICS };

/** Parsed CKM data, embedded at build time. */
const CKM = JSON.parse(ckmRaw) as {
  concepts: {
    id: string;
    name: string;
    what: string;
    properties?: { name: string; type: string; description: string }[];
  }[];
  operations: {
    id: string;
    name: string;
    what: string;
    inputs?: { name: string; type: string; required: boolean; description: string }[];
    outputs?: { text: string };
  }[];
  constraints: { id: string; rule: string; enforcedBy: string }[];
  workflows: { id: string; goal: string; steps: { command?: string; manual?: string }[] }[];
  configSchema: { key: string; type: string; description: string; default?: string }[];
};

/** Map help topics to CKM concept names. */
const TOPIC_TO_CKM: Record<string, string[]> = {
  config: [
    'ManifestConfig',
    'CalVerConfig',
    'SyncConfig',
    'ChangelogConfig',
    'GitHooksConfig',
    'GitConfig',
    'VersioningConfig',
    'VersionGuardConfig',
    'InitOptions',
  ],
  calver: ['CalVerConfig', 'ValidationResult'],
  manifest: ['ManifestConfig', 'ProjectRootResult'],
  hooks: ['GitHooksConfig', 'GitConfig'],
  changelog: ['ChangelogConfig', 'ChangelogValidationResult'],
};

/** Map help topics to CKM operation names. */
const TOPIC_TO_OPS: Record<string, string[]> = {
  config: ['initConfig', 'runWizard', 'runHeadless'],
  calver: ['validate', 'validateVersion'],
  manifest: ['checkHardcodedVersions'],
  hooks: [
    'generateHookScript',
    'checkHooksPathOverride',
    'checkHuskyBypass',
    'checkHookIntegrity',
    'checkEnforceHooksPolicy',
    'runGuardChecks',
  ],
  changelog: ['validateChangelog', 'createTag', 'validateTagForPush'],
};

/**
 * Returns the topic index listing.
 *
 * @remarks
 * Formats topics for terminal display with aligned columns.
 * Includes usage line, topic list, and available flags.
 *
 * @returns Formatted topic list string suitable for terminal output.
 *
 * @example
 * ```ts
 * console.log(getTopicIndex());
 * ```
 *
 * @public
 * @since 0.4.0
 */
export function getTopicIndex(): string {
  const lines = [
    'VersionGuard Help',
    '',
    'Usage: versionguard help [topic] [--json] [--llm]',
    '',
    'Topics:',
  ];

  const maxName = Math.max(...TOPICS.map((t) => t.name.length));
  for (const topic of TOPICS) {
    lines.push(`  ${topic.name.padEnd(maxName + 2)}${topic.summary}`);
  }

  lines.push('');
  lines.push('Flags:');
  lines.push('  --json    Machine-readable CKM output (concepts, operations, config schema)');
  lines.push('  --llm     Full API context for LLM agents (forge-ts llms.txt)');

  return lines.join('\n');
}

/**
 * Returns help content for a specific topic (human-readable).
 *
 * @remarks
 * Looks up the topic by name in the compiled TOPICS array.
 * Returns null when no matching topic is found.
 *
 * @param topicName - The topic name to look up (e.g. `"calver"`, `"hooks"`).
 * @returns The full help text for the topic, or `null` if not found.
 *
 * @example
 * ```ts
 * const content = getTopicContent('calver');
 * if (content) console.log(content);
 * ```
 *
 * @public
 * @since 0.4.0
 */
export function getTopicContent(topicName: string): string | null {
  const topic = TOPICS.find((t) => t.name === topicName);
  return topic?.content ?? null;
}

/**
 * Returns the full API context for LLM consumption.
 *
 * @remarks
 * Returns the embedded `llms.txt` content generated by forge-ts.
 * This is the Level 2 progressive disclosure output intended for
 * LLM agents that need complete operational knowledge.
 *
 * @returns The full llms.txt string embedded at build time.
 *
 * @example
 * ```ts
 * const context = getLlmContext();
 * // Pass to an LLM as system context
 * ```
 *
 * @public
 * @since 0.4.0
 */
export function getLlmContext(): string {
  return llmsSummary;
}

/**
 * Returns CKM-based structured help for machine parsing.
 *
 * @remarks
 * When a topic is specified, returns only the CKM concepts, operations,
 * and config entries relevant to that topic. When no topic, returns
 * the full CKM.
 *
 * @param topicName - Optional topic to filter CKM output. Omit for the full overview.
 * @returns A plain object with CKM concepts, operations, constraints, and config schema.
 *
 * @example
 * ```ts
 * // Full overview
 * const overview = getHelpJson();
 *
 * // Topic-scoped
 * const hooks = getHelpJson('hooks');
 * ```
 *
 * @public
 * @since 0.4.0
 */
export function getHelpJson(topicName?: string): object {
  if (!topicName) {
    return {
      version: CKM.configSchema?.find((c) => c.key === 'version')?.default ?? 'unknown',
      topics: TOPICS.map((t) => ({ name: t.name, summary: t.summary })),
      ckm: {
        concepts: CKM.concepts.length,
        operations: CKM.operations.length,
        constraints: CKM.constraints.length,
        workflows: CKM.workflows.length,
        configSchema: CKM.configSchema.length,
      },
      commands: [
        'init',
        'check',
        'validate',
        'doctor',
        'fix',
        'fix-changelog',
        'sync',
        'bump',
        'tag',
        'hooks install',
        'hooks uninstall',
        'hooks status',
        'help',
      ],
    };
  }

  const conceptNames = TOPIC_TO_CKM[topicName];
  const opNames = TOPIC_TO_OPS[topicName];

  if (!conceptNames) {
    return { error: `Unknown topic: ${topicName}`, topics: TOPICS.map((t) => t.name) };
  }

  const concepts = CKM.concepts.filter((c) => conceptNames.some((n) => c.name === n));
  const operations = CKM.operations.filter((o) => opNames?.some((n) => o.name === n));
  const config = CKM.configSchema.filter((c) => conceptNames.some((n) => c.key?.startsWith(n)));

  return {
    topic: topicName,
    summary: TOPICS.find((t) => t.name === topicName)?.summary,
    concepts,
    operations,
    configSchema: config,
    constraints: CKM.constraints.filter(
      (c) =>
        concepts.some((co) => c.enforcedBy?.includes(co.name)) ||
        operations.some((o) => c.enforcedBy?.includes(o.name)),
    ),
  };
}
