/**
 * CKM (Codebase Knowledge Manifest) type definitions.
 *
 * @remarks
 * These types describe the structure of a `ckm.json` file generated
 * by forge-ts. Any CLI tool can consume this format to provide
 * machine-readable help, auto-generated topic indexes, and
 * LLM-consumable operational knowledge.
 *
 * @packageDocumentation
 */

/**
 * A domain concept extracted from an exported interface or type.
 *
 * @public
 * @since 0.4.0
 */
export interface CkmConcept {
  /** Unique concept identifier (e.g., `'concept-CalVerConfig'`). */
  id: string;
  /** Interface or type name (e.g., `'CalVerConfig'`). */
  name: string;
  /** One-line description from TSDoc summary. */
  what: string;
  /** Properties of the interface, if applicable. */
  properties?: CkmProperty[];
}

/**
 * A property within a concept.
 *
 * @public
 * @since 0.4.0
 */
export interface CkmProperty {
  /** Property name. */
  name: string;
  /** TypeScript type annotation. */
  type: string;
  /** Description from TSDoc. */
  description: string;
}

/**
 * A user-facing operation extracted from an exported function.
 *
 * @public
 * @since 0.4.0
 */
export interface CkmOperation {
  /** Unique operation identifier (e.g., `'op-validate'`). */
  id: string;
  /** Function name (e.g., `'validate'`). */
  name: string;
  /** One-line description from TSDoc summary. */
  what: string;
  /** Function parameters. */
  inputs?: CkmInput[];
  /** Return value description. */
  outputs?: { text: string };
}

/**
 * A function parameter within an operation.
 *
 * @public
 * @since 0.4.0
 */
export interface CkmInput {
  /** Parameter name. */
  name: string;
  /** TypeScript type annotation. */
  type: string;
  /** Whether the parameter is required. */
  required: boolean;
  /** Description from TSDoc `@param` tag. */
  description: string;
}

/**
 * A constraint enforced by the tool.
 *
 * @public
 * @since 0.4.0
 */
export interface CkmConstraint {
  /** Unique constraint identifier. */
  id: string;
  /** The rule being enforced. */
  rule: string;
  /** Function or module that enforces it. */
  enforcedBy: string;
}

/**
 * A multi-step workflow for a common goal.
 *
 * @public
 * @since 0.4.0
 */
export interface CkmWorkflow {
  /** Unique workflow identifier. */
  id: string;
  /** What the workflow achieves. */
  goal: string;
  /** Ordered steps. */
  steps: { command?: string; manual?: string; note?: string }[];
}

/**
 * A config schema entry with type, description, and default.
 *
 * @public
 * @since 0.4.0
 */
export interface CkmConfigEntry {
  /** Dotted key path (e.g., `'CalVerConfig.format'`). */
  key: string;
  /** TypeScript type. */
  type: string;
  /** Description from TSDoc. */
  description: string;
  /** Default value if specified via `@defaultValue`. */
  default?: string;
}

/**
 * The complete Codebase Knowledge Manifest.
 *
 * @remarks
 * Generated by `forge-ts build` from TSDoc annotations.
 * Consumed by CLI tools for structured help output.
 *
 * @public
 * @since 0.4.0
 */
export interface CkmManifest {
  /** Domain concepts (interfaces, types). */
  concepts: CkmConcept[];
  /** User-facing operations (exported functions). */
  operations: CkmOperation[];
  /** Enforced rules. */
  constraints: CkmConstraint[];
  /** Multi-step workflows. */
  workflows: CkmWorkflow[];
  /** Configuration schema entries. */
  configSchema: CkmConfigEntry[];
}

/**
 * An auto-generated topic derived from CKM data.
 *
 * @public
 * @since 0.4.0
 */
export interface CkmTopic {
  /** Topic slug used as CLI argument (e.g., `'calver'`). */
  name: string;
  /** One-line summary. */
  summary: string;
  /** Related concept names from the CKM. */
  concepts: CkmConcept[];
  /** Related operations from the CKM. */
  operations: CkmOperation[];
  /** Related config entries from the CKM. */
  configSchema: CkmConfigEntry[];
  /** Related constraints from the CKM. */
  constraints: CkmConstraint[];
}
